import i18n from 'i18next';
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      ru: {
        translation: {
          "to_come_in": "Войти",
          "register" : "Зарегестрироваться",
          "or" : "или",
          "google" : "Войти через Google",
          "forgot_password" : 'Забыл пароль',
          "reset_the_password" : "Сбросить пароль",
          "Remembered_the_password" : "Вспомнил пароль",
          "Repeat_password" : "Повторите пароль",
          "continue" : "Продолжить",
          "to_your": "На вашу",
          "email_sent_link" : "почту отправлена ссылка",
          "to_reset_your_password" : "для сброса пароля",
          "confirm_mail" : "Подтвердите почту, чтобы активировать аккаунт",
          "if_the_letter_did_not_arrive" : ' Если письмо не пришло, проверьте папку "спам" или',
          "repeat_activation" : "повторите активацию",
          "city_of_residence" : "Город проживания",
          "school_name" : "Название школы",
          "school_number" : "Номер школы",
          "class_number" : "Номер класса",
          "entrance" : "Вход",
          "forgot_address" : " Забыли адрес эл. почты?",
          "app_makers" : " Приложению “Makers” будет предоставлен доступ к вашим данным: имени,адресу электронной почты, языковым настройкам и фото профиля. Прежде чем начать работу с приложением “Makers”, вы можете ознакомиться с его",
          "policy" : " политикой конфиденциальности и условиями использования.",
          "create_an_account" : "Создать аккаунт",


          "adobe_photoshop" : "Курс по Adobe Photoshop",
          "adobe_photoshop-1" : "Вы изучите лучшие и самые современные техники по выделения объектов.",
          "adobe_photoshop-2" : "Вы начнете использовать в работе Гистограмму и круг HSL.",
          "adobe_photoshop-3" : "Вы начнете разбираться в тонкостях настройки программы Photoshop",
          "adobe_photoshop-4" : "Вы научитесь монтировать видео ролики прямо в photoshop",
          "adobe_photoshop-5" : "Вы узнаете что такое синемаграфия и параллакс эффект",
          "adobe_photoshop-6" : "Вы создадите более 7 новых работ для вашего портфолио.",
          "adobe_photoshop-7" : "Продолжительность курса: 2 месяца",
          "adobe_photoshop-8" : "12 видеолекций",
          "adobe_photoshop-9" : "25 000 сом",
          
          // app main page
          "macbook" : "Купи Macbook своей мечты Приходи к нам в Istore.kg",
          "free_courses" : "Бесплатные курсы",
          "Paid_courses " : "Платные курсы",
          "contact" : "Связаться ",
          "send" : "Отправить",
          "personal_area" : "Личный кабинет",
          "favorites" : "Избранное", 
          "test" : "Тест" ,
          "help" : "Помощь",
          "home" : "Главная",
          "Course_schedule" : "Расписание курсов",
          "video_player" : "Видео плеер",
          "go_out" : "Выйти",

          "personal_data" : "Персональные данные",
          "my_courses" : "Мои курсы",
          "test_results" : "Результаты тестов",

          "ui_kit" : "Веб дизайн в Figma. Создание Ui Kit",
          "kit-1" : "Изучение всех инструментов Figma",
          "kit-2" : "Углубленное изучение Figma",
          "kit-3" : "Практика работы в Figma",
          "kit-4" : "Углубленная работа со сложными компонентами",
          "kit-5" : "Продумывание архитектуры проекта",
          "kit-6" : "Создание реального продукта Ui Kit",
          "kit-7" : "Работа с плагинами",
          "kit-8" : "Работа с hot key",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",





        },
      },
      kg: {
        translation: {
          "to_come_in": "Кируу",
          "register" : "Каттоо",
          "or" : "же",
          "google" : 'Google аркылуу кируу',
          "forgot_password" : 'Паролду унутуп калдыңыз',
          "reset_the_password" : "Сырсөздү кайра коюу",
          "Remembered_the_password" : "Сырсөздү эстеди",
          "Repeat_password" : "Сырсөздү кайталаңыз",
           "continue" : "Улантуу",
           "to_your": "Сиздин почтаңызга",
           "email_sent_link" : "сырсөздү калыбына келтирүү ",
           "to_reset_your_password" : "шилтемеси жөнөтүлдү",
           "confirm_mail" : "Каттоо эсебиңизди активдештирүү үчүн электрондук почтаңызды ырастаңыз",
           "if_the_letter_did_not_arrive" : ' Эгер сиз электрондук кат албасаңыз, спам папкаңызды текшериңиз же',
           "repeat_activation" : "кайра активдештирип көрүңүз.",
           "city_of_residence" : "Шаар же жашаган мамлекет",
           "school_name" : "Мектептин аты",
           "school_number" : "Мектептин номери ",
           "class_number" : "Класстын номери ",
           "entrance" : "Чыгуу",
           "forgot_address" : "Эл.почта дарегин унутуп калдым?",
           "app_makers" : " “Makers” колдонмосуна маалыматтарыңызга мүмкүнчүлүк берилет: аты-жөнү, электрондук почта дареги, тил жөндөөлөрү жана профиль сүрөтү. “Makers” колдонмосун баштоодон мурун, аны менен таанышып чыксаңыз болот",
           "policy" : "купуялык саясаты жана пайдалануу шарттары.",
           "create_an_account" : "Эсеп түзүү",

           "adobe_photoshop" : "Курс по Adobe Photoshop",
           "adobe_photoshop-1" : "Сиз объекттерди тандоонун эң мыкты жана заманбап ыкмаларын үйрөнөсүз.",
           "adobe_photoshop-2" : "Сиз гистограмманы жана HSL Circle колдоно баштайсыз.",
           "adobe_photoshop-3" : "Сиз Photoshop орнотуунун татаалдыктарын түшүнө баштайсыз.",
           "adobe_photoshop-4" : "Сиз Photoshop программасында видеоклиптерди кантип орнотууну үйрөнөсүз",
           "adobe_photoshop-5" : "Сиз кинематография жана параллакс эффектиси эмне экенин билесиз",
           "adobe_photoshop-6" : "Сиз портфолиоңуз үчүн 7ден ашык жаңы чыгармаларды жаратасыз.",
           "adobe_photoshop-7" : "Продолжительность курса: 2 месяца",
           "adobe_photoshop-8" : "12 видеолекций",
           "adobe_photoshop-9" : "25 000 сом",

            // app main page
          "macbook" : "Кыялыңыздагы Macbook сатып алыңыз Istore.kg сайтына келиңиз",
          "free_courses" : "Акысыз курстар",
          "Paid_courses " : "Акы төлөнүүчү курстар",
          "contact" : "Байланыш",
          "send" : "Жөнөтүү",

          "personal_area" : "Жеке бөлмө",
          "favorites" : "Сүйүктүүлөр", 
          "test" : "Тест" ,
          "help" : "Жардам",
          "home" : "үй",
          "Course_schedule" : "Акы төлөнүүчү курстар",
          "video_player" : "Курстун тартиби",
          "go_out" : "Чыгуу",

          "personal_data" : "Жеке маалыматтар",
          "my_courses" : "Менин курстарым",
          "test_results" : "Тесттин жыйынтыгы",


          "ui_kit" : "Веб дизайн в Figma. Создание Ui Kit",
          "kit-1" : "Бардык Figma куралдарын изилдөө",
          "kit-2" : "Углубленное изучение Figma",
          "kit-3" : "Практика работы в Figma",
          "kit-4" : "Углубленная работа со сложными компонентами",
          "kit-5" : "Продумывание архитектуры проекта",
          "kit-6" : "Создание реального продукта Ui Kit",
          "kit-7" : "Работа с плагинами",
          "kit-8" : "Работа с hot key",

          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          "" : "",
          

        },
      },
    },
    fallbackLng: 'ru', 
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ["cookie", "localStorage"],
      caches: ["cookie"]
    },
    debug: true,
  });

export default i18n;
